version: '3.8'

services:
  backend:
    build: ./game-review-sentiment-backend
    ports:
      - "5000:5000"
    volumes:
      - ./game-review-sentiment-backend:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - hello-world

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   ports:
  #     - "4040:4040"
  #   environment:
  #     - NGROK_AUTHTOKEN=32MPylzVFD1zt9hHflx2uD8iN4V_72ZmiBG8r7HqGVDfJA8KG
  #   command: http host.docker.internal:8080
  

  hello-world:
    image: alpine:latest  
    command: echo "Hello World"
    
  frontend:
    build: ./game-review-sentiment
    ports:
      - "3000:3000"
    volumes:
      - ./game-review-sentiment:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    

    
    